from app import db
from datetime import datetime

class sepRequest(db.Model):
    id = db.Column(db.BigInteger,primary_key=True,autoincrement=True)
    noKartu = db.Column(db.String(250),nullable=True)
    tglSep = db.Column(db.DateTime,nullable=True)
    ppkPelayanan = db.Column(db.String(250),nullable=True)
    jnsPelayanan = db.Column(db.String(250),nullable=True)
    klsRawat_klsRawatHak = db.Column(db.String(250),nullable=True)
    klsRawat_klsRawatNaik = db.Column(db.String(250),nullable=True)
    klsRawat_pembiayaan = db.Column(db.String(250),nullable=True)
    klsRawat_penanggung_jawab = db.Column(db.String(250),nullable=True)
    noMR = db.Column(db.BigInteger,nullable=True)
    rujukan_asalRujukan = db.Column(db.String(250),nullable=True)
    rujukan_tglRujukan = db.Column(db.DateTime,nullable=True)
    rujukan_noRujukan = db.Column(db.String(250),nullable=True)
    rujukan_ppkRujukan = db.Column(db.String(250),nullable=True)
    catatan = db.Column(db.String(250),nullable=True)
    diagAwal = db.Column(db.String(250),nullable=True)
    poli_tujuan = db.Column(db.String(250),nullable=True)
    poli_eksekutif = db.Column(db.String(250),nullable=True)
    cob = db.Column(db.String(250),nullable=True)
    katarak_katarak = db.Column(db.String(250),nullable=True)
    jaminan_lakaLantas = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_tglKejadian = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_keterangan = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_suplesi_suplesi = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_suplesi_noSepSuplesi = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_suplesi_lokasiLaka_kdPropinsi = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_suplesi_lokasiLaka_kdKabupaten = db.Column(db.String(250),nullable=True)
    jaminan_penjamin_suplesi_lokasiLaka_kdKecamatan = db.Column(db.String(250),nullable=True)
    tujuanKunj = db.Column(db.String(250),nullable=True)
    flagProcedure = db.Column(db.String(250),nullable=True)
    kdPenunjang = db.Column(db.String(250),nullable=True)
    assesmentPel = db.Column(db.String(250),nullable=True)
    skdp_noSurat = db.Column(db.String(250),nullable=True)
    skdp_kodeDPJP = db.Column(db.String(250),nullable=True)
    dpjpLayan = db.Column(db.String(250),nullable=True)
    noTelp = db.Column(db.String(250),nullable=True)
    user = db.Column(db.String(250),nullable=True)
    status_created_sep = db.Column(db.String(250),nullable=True)
    created_at = db.Column(db.DateTime,default=datetime.utcnow)
    updated_at = db.Column(db.DateTime,default=datetime.utcnow)

    def __repr_(self):
        return '<sepRequest {}>'.format(self.name)