"""add db rencana kontrol and rencana ri

Revision ID: 2582ee39c641
Revises: f319de6675e2
Create Date: 2022-02-22 10:32:00.278873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2582ee39c641'
down_revision = 'f319de6675e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rencana_kontrol_response',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('noSuratKontrol', sa.String(length=250), nullable=True),
    sa.Column('tglRencanaKontrol', sa.String(length=250), nullable=True),
    sa.Column('namaDokter', sa.String(length=250), nullable=True),
    sa.Column('noKartu', sa.String(length=250), nullable=True),
    sa.Column('nama', sa.String(length=250), nullable=True),
    sa.Column('kelamin', sa.String(length=250), nullable=True),
    sa.Column('tlgLahir', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rencana_ri_response',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('noSPRI', sa.String(length=250), nullable=True),
    sa.Column('tglRencanaKontrol', sa.String(length=250), nullable=True),
    sa.Column('namaDokter', sa.String(length=250), nullable=True),
    sa.Column('noKartu', sa.String(length=250), nullable=True),
    sa.Column('nama', sa.String(length=250), nullable=True),
    sa.Column('kelamin', sa.String(length=250), nullable=True),
    sa.Column('tlgLahir', sa.String(length=250), nullable=True),
    sa.Column('namaDiagnosa', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rencana_ri_response')
    op.drop_table('rencana_kontrol_response')
    # ### end Alembic commands ###
