"""sep request

Revision ID: 309a91501f82
Revises: 
Create Date: 2022-01-17 10:14:08.478852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309a91501f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sep_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('noKartu', sa.String(length=250), nullable=True),
    sa.Column('tglSep', sa.String(length=250), nullable=True),
    sa.Column('ppkPelayanan', sa.String(length=250), nullable=True),
    sa.Column('klsRawat_klsRawatHak', sa.String(length=250), nullable=True),
    sa.Column('klsRawat_klsRawatNaik', sa.String(length=250), nullable=True),
    sa.Column('klsRawat_pembiayaan', sa.String(length=250), nullable=True),
    sa.Column('klsRawat_penanggung_jawab', sa.String(length=250), nullable=True),
    sa.Column('noMR', sa.BigInteger(), nullable=True),
    sa.Column('rujukan_asalRujukan', sa.String(length=250), nullable=True),
    sa.Column('rujukan_tglRujukan', sa.String(length=250), nullable=True),
    sa.Column('rujukan_noRujukan', sa.String(length=250), nullable=True),
    sa.Column('rujukan_ppkRujukan', sa.String(length=250), nullable=True),
    sa.Column('catatan', sa.String(length=250), nullable=True),
    sa.Column('diagAwal', sa.String(length=250), nullable=True),
    sa.Column('poli_tujuan', sa.String(length=250), nullable=True),
    sa.Column('poli_eksekutif', sa.String(length=250), nullable=True),
    sa.Column('cob', sa.String(length=250), nullable=True),
    sa.Column('katarak_katarak', sa.String(length=250), nullable=True),
    sa.Column('jaminan_lakaLantas', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_tglKejadian', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_keterangan', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_suplesi_suplesi', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_suplesi_noSepSuplesi', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_suplesi_lokasiLaka_kdPropinsi', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_suplesi_lokasiLaka_kdKabupaten', sa.String(length=250), nullable=True),
    sa.Column('jaminan_penjamin_suplesi_lokasiLaka_kdKecamatan', sa.String(length=250), nullable=True),
    sa.Column('tujuanKunj', sa.String(length=250), nullable=True),
    sa.Column('flagProcedure', sa.String(length=250), nullable=True),
    sa.Column('kdPenunjang', sa.String(length=250), nullable=True),
    sa.Column('assesmentPel', sa.String(length=250), nullable=True),
    sa.Column('skdp_noSurat', sa.String(length=250), nullable=True),
    sa.Column('skdp_kodeDPJP', sa.String(length=250), nullable=True),
    sa.Column('dpjpLayan', sa.String(length=250), nullable=True),
    sa.Column('noTelp', sa.String(length=250), nullable=True),
    sa.Column('user', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sep_request')
    # ### end Alembic commands ###
