"""Create Table SEP Response

Revision ID: 933127d291b5
Revises: 309a91501f82
Create Date: 2022-01-31 13:51:36.296085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933127d291b5'
down_revision = '309a91501f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sep_response',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('catatan', sa.String(length=250), nullable=True),
    sa.Column('diagnosa', sa.String(length=250), nullable=True),
    sa.Column('jnspelayanan', sa.String(length=250), nullable=True),
    sa.Column('kelasrawat', sa.String(length=250), nullable=True),
    sa.Column('nosep', sa.String(length=250), nullable=True),
    sa.Column('penjamin', sa.String(length=250), nullable=True),
    sa.Column('peserta_asuransi', sa.String(length=250), nullable=True),
    sa.Column('peserta_hakkelas', sa.String(length=250), nullable=True),
    sa.Column('peserta_jnspeserta', sa.String(length=250), nullable=True),
    sa.Column('peserta_kelmain', sa.String(length=250), nullable=True),
    sa.Column('peserta_nama', sa.String(length=250), nullable=True),
    sa.Column('peserta_nomorkartu', sa.String(length=250), nullable=True),
    sa.Column('peserta_nomr', sa.String(length=250), nullable=True),
    sa.Column('peserta_tgllahir', sa.DateTime(), nullable=True),
    sa.Column('informasi_dinsos', sa.String(length=250), nullable=True),
    sa.Column('informasi_prolanisprb', sa.String(length=250), nullable=True),
    sa.Column('informasi_nosktm', sa.String(length=250), nullable=True),
    sa.Column('poli', sa.String(length=250), nullable=True),
    sa.Column('polieksekutif', sa.String(length=250), nullable=True),
    sa.Column('tglsep', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sep_response')
    # ### end Alembic commands ###
