"""Update Table SEP Response

Revision ID: d3dbb32db3e7
Revises: 933127d291b5
Create Date: 2022-01-31 13:53:03.094663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3dbb32db3e7'
down_revision = '933127d291b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sep_response', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sep_response', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sep_response', 'updated_at')
    op.drop_column('sep_response', 'created_at')
    # ### end Alembic commands ###
