"""Add Status Create SEP

Revision ID: e4f676c1b384
Revises: d3dbb32db3e7
Create Date: 2022-02-03 09:55:42.866410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f676c1b384'
down_revision = 'd3dbb32db3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sep_request', sa.Column('status_created_sep', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sep_request', 'status_created_sep')
    # ### end Alembic commands ###
