"""Add noLP

Revision ID: f319de6675e2
Revises: 94cd14034298
Create Date: 2022-02-03 10:37:24.363985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f319de6675e2'
down_revision = '94cd14034298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sep_request', sa.Column('jaminan_noLP', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sep_request', 'jaminan_noLP')
    # ### end Alembic commands ###
